# Script for importing and consolidating files from the ICHEC cluster. At the
# moment, the data generated by the model on the cluster are output as 
# individual text files. At the moment, there are only a few, but eventually
# there may be hundreds or even thousands. 

# TODO: figure out why this is requiring me to set a working directory.

library(tidyverse)

# path <- "~/Desktop/Local/Mackerel/Mackerel Data/ICHEC/27feb2020"  # desktop
setwd("~/Desktop/DO NOT ERASE/1NUIG/Mackerel/Mackerel Data/ICHEC/06Apr2020")  # laptop
path <- "~/Desktop/DO NOT ERASE/1NUIG/Mackerel/Mackerel Data/ICHEC/06Apr2020"  # laptop

# Testing if data import will work with one file ------------------------------
# setwd(path)  # laptop
# test <- read.table("sep_output0.txt", sep = "")


# Import all files ------------------------------------------------------------

# Create a list of all of the files in this location, read them as tables,
# and consolidate them into one. 

# 27 Feb - data generated by multiple runs of the model has a weird first index
# coumn

# TODO: Change end of file path to desired folder
data <- list.files(path, pattern="*.txt") %>% map_df(~read.table(., sep = ""))

path2 <- "~/Desktop/DO NOT ERASE/1NUIG/Mackerel/Mackerel Data/ICHEC_data_06Apr20.csv"  # laptop
write.csv(data, path2)
