# Script for importing and consolidating files from the ICHEC cluster. At the
# moment, the data generated by the model on the cluster are output as 
# individual text files. At the moment, there are only a few, but eventually
# there may be hundreds or even thousands. 

library(tidyverse)

# Testing if data import will work with one file ------------------------------

setwd("~/Desktop/Local/Mackerel/Mackerel Data/ICHEC/27feb2020")
test <- read.table("sep_output0.txt", sep = "")

# Create a list of all of the files in this location, read them as tables,
# and consolidate them into one. 

# 27 Feb - data generated by multiple runs of the model has a weird first index
# coumn

# TODO: Change end of file path to desired folder
data <- list.files("~/Desktop/Local/Mackerel/Mackerel Data/ICHEC/27feb2020",
                  pattern="*.txt") %>%
  map_df(~read.table(., sep = ""))
  