# Script for importing and consolidating files from the ICHEC cluster. At the
# moment, the data generated by the model on the cluster are output as 
# individual text files. At the moment, there are only a few, but eventually
# there may be hundreds or even thousands. 

library(tidyverse)

# Create a list of all of the files in this location, read them as tables,
# and consolidate them into one.
# TODO: Change end of file path to desired folder
data <- list.files("~/Desktop/Local/Mackerel/Mackerel Data/ICHEC/25feb2020",
                  pattern="*.txt") %>%
  map_df(~read.table(., sep = ""))
  